apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: gcr.io/sharp-ring-407510/calc-app:latest
        ports:
        - containerPort: 5000
